Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using StaffManagement.Data;
using StaffManagement.Models;

namespace StaffManagement.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ApplicationDbContext _context = new();

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            var applicationDbContext = _context.Accounts.Include(a => a.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Accounts/Create
        public IActionResult Create()
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index");
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name");
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string Username, string Password, bool IsAdmin, bool IsActive, int UserId)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index");
            }
            var account = new Account
            {
                Username = Username,
                Password = Password,
                IsActive = IsActive,
                IsAdmin = IsAdmin,
                UserId = UserId
            };
            var find = _context.Accounts.FirstOrDefault(a => (a.Username == account.Username || a.UserId == UserId));
            if (ModelState.IsValid && find==null)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Message"] = "Account with Username or User is existed";
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", account.User.Id);
            return View(account);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, string Username, string Password, bool IsAdmin, bool IsActive)
        {
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            var account = _context.Accounts.FirstOrDefault(d => d.Id == Id);
            if (account != null)
            {
                account.Username = Username;
                account.Password = Password;
                account.IsActive = IsActive;
                account.IsAdmin = IsAdmin;
            }
            else
            {
                ViewData["Message"] = "Account not exist";
                return View(account);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Entry(account).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(account);
        }

        // GET: Accounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index");
            }
            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                _context.Accounts.Remove(account);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StaffManagement.Data;
using StaffManagement.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace StaffManagement.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context = new();

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if(role!="Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            var user = _context.Users.Include(d => d.Department);
            return View(await user.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Users.Include(d => d.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        public IActionResult Create()
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string StaffNumber, string Name, string PhoneNumber, string Email, DateOnly DOB, string Address, int DepartmentId, string Description)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            var user = new User
            {
                Address = Address,
                Name = Name,
                PhoneNumber = PhoneNumber,
                Email = Email,
                DOB = DOB,
                DepartmentId = DepartmentId,
                Description = Description,
                StaffNumber = StaffNumber
            };
            var find = _context.Users.FirstOrDefault(u => u.Name==Name || u.Email==Email || u.StaffNumber==StaffNumber);
            if (ModelState.IsValid && find==null)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();                
                return RedirectToAction(nameof(Index));
            }
            ViewData["Message"] = "User existed with Name or Email or StaffNumber";
            ViewData["Department"] = new SelectList(_context.Departments, "Id", "Name");
            return View(user);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Users.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name");
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, string StaffNumber, string Name, string PhoneNumber, string Email, DateOnly DOB, string Address, int DepartmentId, string Description)
        {
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            var staff = _context.Users.FirstOrDefault(x => x.Id == Id);
            if (staff != null)
            {
                staff.Name = Name;
                staff.PhoneNumber = PhoneNumber;
                staff.Description = Description;
                staff.Email = Email;
                staff.DOB = DOB;
                staff.Address = Address;
                staff.DepartmentId = DepartmentId;
                staff.StaffNumber = StaffNumber;
            }
            else
            {
                ViewData["Message"] = "Staff not exist";
                return View(staff);
            }
            var find = _context.Users.FirstOrDefault(u => u.Name == Name || u.Email == Email || u.StaffNumber == StaffNumber);
            if (ModelState.IsValid && find==null)
            {
                try
                {
                    _context.Entry(staff).State= EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Message"] = "Duplicated with Name or Email or StaffNumber";
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name");
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Users.Include(d=>d.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = HttpContext.Session.GetString("Role");
            var AccountID = HttpContext.Session.GetInt32("AccountID");
            if (AccountID == null || AccountID == -1)
            {
                return RedirectToAction("Login", "Home");
            }
            if (role != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            var staff = await _context.Users.FindAsync(id);
            if (staff != null)
            {
                _context.Users.Remove(staff);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Staff Management System</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Admin/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Admin/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Admin/plugins/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="~/Admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        @{
            var role = HttpContextAccessor.HttpContext.Session.GetString("Role");
            var name = HttpContextAccessor.HttpContext.Session.GetInt32("Name");
            var accountid = HttpContextAccessor.HttpContext.Session.GetInt32("AccountID");
            var userid = HttpContextAccessor.HttpContext.Session.GetInt32("UserID");
        }
        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/Admin/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <a class="dropdown-item" asp-action="LogOut" asp-controller="Home">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/Admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Staff Application</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/admin/dist/img/_08e794dd-7a59-4df3-a95b-3696401e324a.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@name</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item menu-open">
                            <a asp-action="Index" asp-controller="Home" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>
                        </li>
                        @if (role == "Admin")
                        {
                            <li class="nav-item">
                                <a asp-controller="Users" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Staff Management
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Accounts" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Account Management
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Departments" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Department Management
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Schedules" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Schedule Management
                                    </p>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-controller="Users" asp-action="Edit" asp-route-id="@userid" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        User Detail
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Accounts" asp-action="Edit" asp-route-id="@accountid" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Account Detail
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Departments" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Department Management
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Schedules" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>
                                        Schedule Management
                                    </p>
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year <a href="">Designed and Developer by PhamLong</a>.</strong>
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Admin/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Admin/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Admin/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Admin/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/Admin/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Admin/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Admin/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Admin/plugins/moment/moment.min.js"></script>
    <script src="~/Admin/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/Admin/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Admin/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Admin/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Admin/dist/js/pages/dashboard.js"></script>
    <script src="~/Admin/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Admin/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Admin/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Admin/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Admin/plugins/jszip/jszip.min.js"></script>
    <script src="~/Admin/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/Admin/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/Admin/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Admin/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/Admin/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>